#!/usr/bin/env bash 
while true 
do
x=$(shuf -n 1 slang.txt)
while read -r badword 
do
x=$(echo "$x" | sed "s/$badword/*****/g")
done <badwords.txt
echo "$x" | base64 >> /opt/Bashrot_vault/$(date +%s).txt
sleep 30
done
